chore: revert wild in the dev shell
Commands like `cargo nextest run` fail with:

```
  error: creating test list failed

Caused by:
  for `fedimint-dummy-tests::fedimint_dummy_tests`, command `/home/dpc/lab/fedimint/fedimint/target-nix/debug/deps/fedimint_dummy_tests-e1ac9f7caff
f2a1b --list --format terse` exited with code 127
--- stdout:

--- stderr:
/home/dpc/lab/fedimint/fedimint/target-nix/debug/deps/fedimint_dummy_tests-e1ac9f7cafff2a1b: error while loading shared libraries: libstdc++.so.6:
cannot open shared object file: No such file or directory

---
```

and there can be lots of reasons for it, possibly related to Nix
wrapping described in: https://github.com/davidlattimore/wild?tab=readme-ov-file#nix

which compounds with flakebox complexity, etc. which I don't have
time to tackle now.